[workspace]
authors = ["khshmt <khshmt2@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "ros2_pixi_playground"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[dependencies]
cmake = "*"
ninja = "*"
pkg-config = "*"
compilers = "*"

ros-humble-rclcpp = ">=16.0.13,<17"
ros-humble-std-msgs = ">=4.9.0,<5"
ros-humble-message-filters = ">=4.3.7,<5"
ros-humble-rosbag2-storage-default-plugins = ">=0.15.14,<0.16"
ros-humble-rosbag2-cpp = ">=0.15.14,<0.16"
ros-humble-rosbag2-storage-mcap = ">=0.15.14,<0.16"
ros-humble-sensor-msgs = ">=4.9.0,<5"
ros-humble-vision-opencv = ">=3.2.1,<4"
ros-humble-cv-bridge = ">=3.2.1,<4"
ros-humble-image-transport = ">=3.1.12,<4"
rerun-sdk = ">=0.29.2,<0.30"
librerun-sdk = ">=0.29.2,<0.30"

[tasks]
clean = "rm -rf build"
config = "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release"
build = "cmake --build build"

publisher = "build/publisher"
subscriber = "build/subscriber"
usbCameraPublisher = "build/usbCameraPublisher"
visualizer = "build/visualizer"
